### ISSUE TITLE
recompile

### ISSUE THREAD

**Issue by sylvainpaquet** [Jay-Rad/Remotely#100]
Hello jay-rad
I made the changes and recompile
Do I have to redo the installation or simply copy the files found in the wwwroot folder on ubuntu

thank you

**Comment by sylvainpaquet** [comment]
Jay-rad

here is what i did
I modified the schtml files then recompiled, I renamed the old wwwroot of my server then copied the new
I restarted nginx but nothing changes
Is my method the right one or should I do it differently

thank you

**Comment by Jay-Rad** [comment]
Hello.

Please see the README section "Build Instructions".  You need to copy the entire contents of the output directory.

- Jared
