### ISSUE TITLE
Not seeing any logs in the Event Logs

### ISSUE THREAD

**Issue by snowtr** [Jay-Rad/Remotely#11]
Running on Server 2012 R2 and not see any logs from Remotely in Event Logs.

I'm happy to test some things but I'm not sure where to go.  I need this feature working so I can figure out my emailing issues.

**Comment by Jay-Rad** [comment]
The EventLogs table only captures events that I've explicitly sent to it.  I'm adding Windows Event Log provider to capture other internal logs generated by ASP.NET Core, which are currently only being sent to the console (and must be redirected to capture to file).

Log levels and other options are configurable within appsettings.json.  More information can be found here:  https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.2

I'll close this out when I have a new build published that includes the Windows Event Log provider.

**Comment by Jay-Rad** [comment]
Commit: 08d3f4b904ef52df4059efa5f5f3f04b72d82f44

**Comment by Jay-Rad** [comment]
The new server package has been published to https://remotely.lucency.co/.
