### ISSUE TITLE
Emails not sending because of coded SSL requirement on SMTP

### ISSUE THREAD

**Issue by snowtr** [Jay-Rad/Remotely#12]
New installation on Server 2012 R2
I setup the SMTP settings in the config file but when it tried to send, it was always failing to a connection timeout issue
My 'receive connector' in Exchange is what I setup to allow connections and I specifically took off the ability to receive over SSL because I was using the connector for devices that don't support SSL
This caused an error that I could not find on the Remotely server because of logging issues but in Exchange, it logged as a connection timeout.
I did notice that in this file, there is the setting 'mailClient.EnableSsl = true;' which I guess enforces SSL always and that should be either an option for the user in a config file or if you can find another setting, try to use SSL when available but still send if not there:
Remotely/Remotely_Server/Services/EmailSender.cs

**Comment by Jay-Rad** [comment]
I'm adding an option in appsettings.json for this.  I'll close this out when I've released the new build.

**Comment by Jay-Rad** [comment]
Commit: 08d3f4b904ef52df4059efa5f5f3f04b72d82f44

**Comment by Jay-Rad** [comment]
The new server package has been published to https://remotely.lucency.co/.
