### ISSUE TITLE
Windows Client with X86 support

### ISSUE THREAD

**Issue by gvsurenderreddy** [Jay-Rad/Remotely#13]
Hello sir can you make binary for X86 windows please

**Comment by Jay-Rad** [comment]
There is already a 32-bit client.

**Comment by gvsurenderreddy** [comment]
I have checked there is only one Portable Client for Windows it doesn't state its X64 or X32

**Comment by gvsurenderreddy** [comment]
Hello brother can you give me release link please for win32bit sir

**Comment by Jay-Rad** [comment]
The latest releases can be downloaded here: https://remotely.lucency.co/#serverFiles

**Comment by gvsurenderreddy** [comment]
Hello sir ,We have about 500 PC running puppy linux we are using teamviewer and anydesk. If you could help me for i486 and i686 would be nice for me .Or if u can tell how to compile for x32 linux would be nice.Please help sir
