### ISSUE TITLE
Agent install failing on Ubuntu 16.04 - at creating the service

### ISSUE THREAD

**Issue by Trouble123** [Jay-Rad/Remotely#14]
I am trying to install the agent onto a linux 16.04 machine, and its failing to install the service. I set the shell script with set -x so i can see where the issue is, and its failing here:
`  inflating: System.Xml.ReaderWriter.dll  
  inflating: System.Xml.Serialization.dll  
  inflating: System.Xml.XDocument.dll  
  inflating: System.Xml.XmlDocument.dll  
  inflating: System.Xml.XmlSerializer.dll  
  inflating: System.Xml.XPath.dll    
  inflating: System.Xml.XPath.XDocument.dll  
  inflating: WindowsBase.dll         
+ chmod +x ./Remotely_Agent
+ chmod +x ./ScreenCast/Remotely_ScreenCast.Linux
+ cat
+ echo Creating service...
Creating service...
Install-Linux-x64.sh: 47: Install-Linux-x64.sh: Syntax error: "(" unexpected`

Looking at the shell script, i copied/pasted the lines into the shell, and it installed the service and started it without issue:
`root@remotely_01:/tmp# usersArr=($(users))
root@remotely_01:/tmp# targetUser=${usersArr[0]}
root@remotely_01:/tmp# cat > /etc/systemd/system/remotely-agent.service << EOL
> [Unit]
> Description=The Remotely agent used for remote access.
> 
> [Service]
> WorkingDirectory=/usr/local/bin/Remotely/
> ExecStart=/usr/local/bin/Remotely/Remotely_Agent
> Restart=always
> RestartSec=10
> Environment=DISPLAY=:0
> Environment="XAUTHORITY=/home/$targetUser/.Xauthority"
> 
> [Install]
> WantedBy=graphical.target
> EOL
root@remotely_01:/tmp# systemctl enable remotely-agent
systemctl start remotely-agentCreated symlink /etc/systemd/system/graphical.target.wants/remotely-agent.service â†’ /etc/systemd/system/remotely-agent.service.
root@remotely_01:/tmp# systemctl start remotely-agent
`

**Comment by Jay-Rad** [comment]
This is an old version of the script.  Please try the latest one.

Also, only Ubuntu 18.04+ has been tested.
