### ISSUE TITLE
How to change server listening IP/port on Linux?

### ISSUE THREAD

**Issue by ghaberek** [Jay-Rad/Remotely#16]
I already have an Nginx reverse proxy set up on another machine where I can manage all my Let's Encrypt certs in one place. I'd like to use that server to act as the frontend for Remotely which runs on its own machine. How do I make it so that the Remotely listens on `*:5000` instead of `localhost:5000`?

**Comment by Jay-Rad** [comment]
There are multiple ways to do it.  Here's the documentation:  https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-2.2#endpoint-configuration

So, for example, in /etc/systemd/system/remotely.service, add the following line:
`Environment=ASPNETCORE_URLS=http://*:5000`

Hope that helps.  :)

**Comment by ghaberek** [comment]
That worked perfectly, thanks!
