### ISSUE TITLE
How to launch Remotely_Server.exe as service?

### ISSUE THREAD

**Issue by i3laze** [Jay-Rad/Remotely#2]
Hello again!

I'm hosting on IIS 8.5 (Server 2012R2).
http://localhost:5000 only works when Remotely_Server.exe is launched (with user logged on).
Any way to make it run as NT-service or through IIS configuration?

How about implementing "remotely_server.exe --install"?

Seems, I'm going NSSM.exe again for now.

**Comment by Jay-Rad** [comment]
Remotely is configured to run behind IIS or Nginx.  At this time, I won't be pursuing a self-hosted configuration using ASP.NET Core's built-in web server (Kestrel).

When running behind IIS, you'd access it using whatever port the IIS site is configured to use.

Please make sure you have the [.NET Runtime](https://dotnet.microsoft.com/download) installed (which contains the IIS module) and have followed the [Microsoft docs for hosting in IIS](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.2).

Unfortunately, I don't have spare time or resources for testing in Windows Server 2012R2.
