### ISSUE TITLE
No Remotely_Desktop.exe in outdir folder

### ISSUE THREAD

**Issue by tedxuyuan** [Jay-Rad/Remotely#20]
After run powershell to publish, there is no Remotely_Desktop.exe in wwwroot/download folder.

**Comment by Jay-Rad** [comment]
The Publish.ps1 script doesn't build the *.Win projects.  Those projects must be built with msbuild.exe or Visual Studio.

I could potentially search the registry for the MSBuild path in the Publish script.  Just haven't been able to look into it yet.
