### ISSUE TITLE
Segmenting Client Sessions

### ISSUE THREAD

**Issue by harrisalvi** [Jay-Rad/Remotely#25]
Hi Jared,

First and foremost, thank you for working on this project, I have not implemented it yet but it looks very promising. Do you know if it’s possible to segment groups of client users/machines in the web client? For example, if I have different organizations I am managing is it possible to securely segment them? Also has this project been pentested? I can help to test this application for any vulnerabilities, especially when exposed via the internet. 

Thanks

**Comment by Jay-Rad** [comment]
Thanks for the comments.

The categorization of endpoints is pretty basic and roughly thrown together.  Just to keep terminology straight, the top-level "container" in Remotely is called an Organization.  That really should be changed to Provider (as in IT service provider).  It separates the accounts in a multi-tenant setup, such as the demo server.

Most people running their own server for their own use will only have one organization.

All users and device endpoints go into that organization.  You can label/categorize the devices with tags.

Permission groups can be used to restrict access to devices.  Any device that has a permission group applied can only be accessed by users in the same group, or by admins.  The groups are set up in the Account - Organization section.  Then you use AddGroup/RemoveGroup in the console to manage the devices.

It's pretty awkward.  I was going to do another pass at group management, but I ended up running out of time/motivation.  I'm really busy lately with my real job and family/kids.

So, maybe some day I'll revisit it.  And no, it hasn't been pentested or anything.
