### ISSUE TITLE
How do i update a Windows Install

### ISSUE THREAD

**Issue by danmed** [Jay-Rad/Remotely#32]
I'm a bit lost how to update a Windows installation of Remotely.. it's all working great but i've noticed some updated stuff in the github and wondering how i would go about updating..do i just run the install file again?

**Comment by Jay-Rad** [comment]
You don't need to run the install again.  Just stop the web server, then copy/paste/overwrite the server files with the new ones in the ZIP.  Be sure to back up the whole thing first, though, so you can roll back if there's an issue.

A word of caution when updating.  Sometimes, I'll make a change to the underlying data structures that prevents automatic migration of the database.  In those situations, the database will have to be thrown out and rebuilt, and the data would need to be migrated manually.

Commercial/mature products take measures to prevent these kinds of changes and develop migration strategies when they're necessary.  I don't have the time for all that this early in the project.  So changes are kind of fast and loose, sometimes breaking things.

Hopefully I'll get to a point where it's no longer like that.  We'll see.  Until then, just remember to back up!  :)

**Comment by meyerje** [comment]
I just updated from the last August build to the new September build on a Windows server and am getting a connection error now whenever we try to remotely connect.  I'm wondering what is the best route to update the server and/or migrate that data?
