### ISSUE TITLE
Audio Button cannot transfer windows sound

### ISSUE THREAD

**Issue by dotnethii** [Jay-Rad/Remotely#34]

**Comment by irreleph4nt** [comment]
Tested on Windows 8.1 x64 with no issues - works!

**Comment by Jay-Rad** [comment]
Thanks for getting to my backlog, @irreleph4nt .

The OP (and his/her previous account) has been blocked from this repo.  They keep trying to get people to build voice chat for them.  It's really weird.

But yeah, this will work when speakers are plugged in and the audio device is working.
