### ISSUE TITLE
Clients don't register with account

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#35]
Hi,
I have downloaded and tried the agent Local and on tryout server, I can't see the device on both servers, I know that devices register themselves with the server using organization ID, but where shall I put this ID as there is no place to enter account details on the client.

Thanks.

**Comment by irreleph4nt** [comment]
It seems like this info is prepopulated when you download the files from the "Client Downloads" page. Here is what I have done:

1. Update Powershell version on Windows 8 (you probably don't have to)
2. Login to the tryout server, go to account and create an Organisation
3. Download the Poweshell Agent installer from "Client Downloads"
4. Run the installer
5. Refresh Grid view

You can also check the contents of the following file (x64 path) for correct Device, Host and Organisation IDs:
`C:\Program Files\Remotely\ConnectionInfo.json`

**Comment by Jay-Rad** [comment]
Thanks, @irreleph4nt !

This is correct.  The PowerShell install scripts are only available when signed in, and the organization ID is automatically inserted into the script each time it's downloaded.

And again correct: The script saves the information in C:\Program Files\Remotely\ConnectionInfo.json.

If the above isn't working, please let me know, and I'll look into it.  It's currently working for me on my test server and the public server.
