### ISSUE TITLE
Remotely session on Windows does not survive user logout

### ISSUE THREAD

**Issue by irreleph4nt** [Jay-Rad/Remotely#36]
Hi,

First of all, thank you so much for creating this project! I love the idea of having something like this and self-hosting such a solution really is the icing on the cake! :)

I have upgraded my Powershell version to 5.1 on a Windows 8.1 x64 VM and installed the Agent. Everything works fine until the user logs out, which is when Remotely goes into a "Reconnecting" loop. It takes a disconnect from Remotely and a new session for the Windows Login screen to reappear.

**Comment by Jay-Rad** [comment]
Hi!

You're very welcome!  Thanks for your helpful posts on the other topics.

Yeah, this has been on my internal to-do list for a while.  I'll make some time to look into it soon.  :)

**Comment by Jay-Rad** [comment]
This has been fixed in commit b70976034c2bd885a7d5e6c12d2c0f162c4b364e.
