### ISSUE TITLE
The RemoteControl page needs a "back to home" button

### ISSUE THREAD

**Issue by irreleph4nt** [Jay-Rad/Remotely#37]
Hi,

When a session ended I am redirected back to the RemoteControl page on the tryout server. What would be really handy to have in that case is something like a "back to home" button which takes me back to the grid view that I came from before I started the session.
Currently Remotely opens a new tab when you start a session which I personally don't find very pratical. This forces me to go back and find the single Remotely tab I have not started a session on.

**Comment by Jay-Rad** [comment]
I thought I commented on this.  Apparently I forgot to hit the green button or something.

I agree that opening in new tabs isn't ideal.  My reasoning behind it was to make it easy to open multiple remote control sessions, or open a session and still use the console.

What if the remote control session were opened on the main page, but in a new tab next to "Console" and "Grid" tabs?  Then each tab could have a Fullscreen button.  I'm not sure how difficult the change would be until I looked into it, but it's something I've been kicking around.

**Comment by xcracing** [comment]
Personally, I like the design choice of opening in new tabs for my use, however I don't fire up sessions to all my hosts - only the one(s) I need at the time.

Maybe a simple fix to help the previous poster would be to put the machine name in the page title?

**Comment by irreleph4nt** [comment]
That sounds like a good idea indeed.

**Comment by Jay-Rad** [comment]
Great suggestion, @xcracing !

I'll include this in the next update.  I'll comment here again when it's completed.

**Comment by Jay-Rad** [comment]
This has been included in commit 1617865049b0a47e1e6bc55ff0f2d36ed22ac155.  New tabs for remote control sessions now have the machine name in the title.
