### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by Brantlab** [Jay-Rad/Remotely#38]
Deployed on ubuntu 18.04 and ran the setup sh but I get 502 bad gateway.

**Comment by Brantlab** [comment]
`remotely@remotely:~/Remotely-master/Server$ sudo tail -30 /var/log/nginx/error.log
[sudo] password for remotely: 
2019/06/27 04:21:14 [error] 10460#10460: *3 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "remotely.example.com"
2019/06/27 04:21:14 [error] 10460#10460: *3 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "remotely.example.com"
2019/06/27 04:21:15 [error] 10460#10460: *3 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "remotely.example.com", referrer: "http://remotely.example.com/"
2019/06/27 04:23:27 [notice] 11660#11660: signal process started
2019/06/27 04:23:42 [notice] 11726#11726: signal process started
2019/06/27 04:23:55 [notice] 11731#11731: signal process started
2019/06/27 04:26:33 [error] 11732#11732: *10 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-outside>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "remotely.example.com"
2019/06/27 04:26:33 [error] 11732#11732: *10 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-outside>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "remotely.example.com"
2019/06/27 04:26:33 [error] 11732#11732: *13 no live upstreams while connecting to upstream, client: <IP-ADDRESS-outside>, server: remotely.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "remotely.example.com", referrer: "http://remotely.example.com/"
2019/06/27 04:28:29 [notice] 12933#12933: signal process started
2019/06/27 04:28:34 [notice] 13002#13002: signal process started
2019/06/27 04:28:38 [notice] 13007#13007: signal process started
2019/06/27 04:28:40 [notice] 13012#13012: signal process started
2019/06/27 04:28:47 [notice] 13017#13017: signal process started
2019/06/27 04:29:00 [error] 13018#13018: *17 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "remotely.example.com"
2019/06/27 04:29:00 [error] 13018#13018: *17 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "remotely.example.com"
2019/06/27 04:29:01 [error] 13018#13018: *17 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "remotely.example.com", referrer: "https://remotely.example.com/"
2019/06/27 04:29:05 [error] 13018#13018: *17 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "remotely.example.com"
2019/06/27 04:29:05 [error] 13018#13018: *17 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "remotely.example.com", referrer: "https://remotely.example.com/"
2019/06/27 04:31:48 [error] 13018#13018: *23 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "remotely.example.com"
2019/06/27 04:31:48 [error] 13018#13018: *23 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "remotely.example.com"
2019/06/27 04:31:49 [error] 13018#13018: *23 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "remotely.example.com", referrer: "https://remotely.example.com/"
2019/06/27 04:39:51 [error] 13018#13018: *29 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "remotely.example.com"
2019/06/27 04:39:51 [error] 13018#13018: *29 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "remotely.example.com"
2019/06/27 04:39:52 [error] 13018#13018: *29 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "remotely.example.com", referrer: "https://remotely.example.com/"
2019/06/27 04:43:39 [error] 1313#1313: *1 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:5000/", host: "remotely.example.com"
2019/06/27 04:43:39 [error] 1313#1313: *1 connect() failed (111: Connection refused) while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://[::1]:5000/", host: "remotely.example.com"
2019/06/27 04:43:40 [error] 1313#1313: *1 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "remotely.example.com", referrer: "https://remotely.example.com/"
2019/06/27 04:43:43 [error] 1313#1313: *1 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET / HTTP/1.1", upstream: "http://localhost/", host: "remotely.example.com"
2019/06/27 04:43:44 [error] 1313#1313: *1 no live upstreams while connecting to upstream, client: <IP-ADDRESS-Local>, server: remotely.example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "http://localhost/favicon.ico", host: "remotely.example.com", referrer: "https://remotely.example.com/"
`

**Comment by Brantlab** [comment]
sudo tail -30 /var/log/nginx/error.log

https://pastebin.com/d576haUZ

**Comment by Brantlab** [comment]
Didn't mean to close it.

**Comment by Jay-Rad** [comment]
It looks like the Nginx configuration was set up with "remotely.example.com" as the host name.  The host name needs to be an actual URL/IP that points to the machine/VM, or the connection will be rejected.

This is true for any Nginx server that wants to host multiple sites on one machine (not just a Remotely thing).  Since I don't know ahead of time if you intend to host multiple sites, it's configured to only accept traffic for a specific host name.  You can manually change the Nginx configuration to "catch all" if you'd prefer that.

**Comment by Brantlab** [comment]
I whitelisted the private info.... Sorry I should of specified.

**Comment by Brantlab** [comment]
Let me give you a better description. 

I deployed a brand new install of Ubuntu of 18.04 
Downloaded and unzipped the repo
Ran the Remotely_Server_Install.sh with sudo.
Followed the prompts 
script finished and I went to domain remote.example.com < protecting my domain by not posting it....
502 Gateway error

**Comment by Jay-Rad** [comment]
Sorry for the misunderstanding.  I get a lot of emails where people literally enter "example.com," so I just assumed.  My bad.

I just tested deploying on a fresh VM, and all went smoothly.  Could you try checking the output of the following?

nginx -t
systemctl status remotely
wget --spider localhost:5000  (unless port was changed)

What are the results of those?

**Comment by Brantlab** [comment]
remotely@remotely:~$ sudo nginx -t
[sudo] password for remotely:
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful


remotely@remotely:~$ systemctl status remotely
● remotely.service - Remotely Server
   Loaded: error (Reason: Exec format error)
   Active: inactive (dead)

Jun 27 06:56:12 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:13 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:14 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:14 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:14 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:54 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:54 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:56 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:57 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
Jun 27 06:56:57 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path
lines 1-14/14 (END)
● remotely.service - Remotely Server
   Loaded: error (Reason: Exec format error)
   Active: inactive (dead)

Jun 27 06:56:12 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:13 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:14 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:14 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:14 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:54 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:54 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:56 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:57 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.
Jun 27 06:56:57 remotely systemd[1]: /etc/systemd/system/remotely.service:5: Working directory path '' is not absolute.

remotely@remotely:~$ wget --spider localhost:5000
Spider mode enabled. Check if remote file exists.
--2019-06-27 19:59:53--  http://localhost:5000/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:5000... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:5000... failed: Connection refused.

remotely@remotely:~$ wget --spider localhost:80
Spider mode enabled. Check if remote file exists.
--2019-06-27 20:00:02--  http://localhost/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 612 [text/html]
Remote file exists and could contain further links,
but recursion is disabled -- not retrieving.

remotely@remotely:~$ wget --spider localhost:443
Spider mode enabled. Check if remote file exists.
--2019-06-27 20:00:09--  http://localhost:443/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:443... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:443... connected.
HTTP request sent, awaiting response... 400 Bad Request
Remote file does not exist -- broken link!!!

**Comment by Jay-Rad** [comment]
It looks like the service isn't starting because the WorkingDirectory is blank (which means ExecStart is likely incorrect as well).

The first prompt of the install script asks for the root path where the app is installed (i.e. where the Remotely_Server.dll is located).  I might want to make the prompt a little more clear.  It sets it in the service file like so:

```
[Service]
WorkingDirectory=$appRoot
ExecStart=/usr/bin/dotnet $appRoot/Remotely_Server.dll
```

Check your service config (/etc/systemd/system/remotely.service) and make sure those values have the absolute path in them.  Let me know if that was it.  :)

**Comment by Jay-Rad** [comment]
Actually, looking at this again, that variable is used for several other commands.  You might just want to run the script again if that variable was indeed blank.

**Comment by Brantlab** [comment]
Here is a video of what I am doing during the re-run of the script. This link expires in 1 day. We aren't using this in production or anything. Its for my homelab I just work from home so it was easier to send it this way. 
https://beaconcu.sharefile.com/d-sa1751e3ad274333a

**Comment by Jay-Rad** [comment]
When it's asking for the app path, it looks like you're entering an empty string.  It's expecting the absolute path to where you want to install the app/website.  See here:  https://lucency.co/ImageShare/?view=lvwjryji1p2

That path is stored in a variable and used throughout the rest of the script.

**Comment by Brantlab** [comment]
10/10 User error. Works now! Thanks! I thought when it mentioned "typically /var..." that was the default and if you wanted something different please enter it now. Bad on me for making the assumption.

**Comment by Jay-Rad** [comment]
No problem!

Now that you mention it, I think someone else gave me similar feedback once.

I added that as the "default" location, so it behaves you described above.  Thanks!
