### ISSUE TITLE
Ubuntu 18.04 install

### ISSUE THREAD

**Issue by danmed** [Jay-Rad/Remotely#39]
Either i'm being really dense, or the instructions for installing on Ubuntu 18.04 seem to be missing some fundamental steps...

Are you assuming Apache2 is installed already before the install script is run? Or will this run on a OOTB Ubuntu 18.04 install with no extras?

**Comment by Jay-Rad** [comment]
The [server install script](https://github.com/Jay-Rad/Remotely/blob/master/Utilities/Remotely_Server_Install.sh) installs, configures, and uses Nginx.
