### ISSUE TITLE
Portable Remotely_Desktop doesn't appear on a grid

### ISSUE THREAD

**Issue by i3laze** [Jay-Rad/Remotely#4]
I've launched client locally on the server, it connected successfully to http://localhost:5000 and is manageable, however didn't appear on a Grid.  Console also tells, that no service is installed around.

Looks like only clients deployed as service supported..?

P.S. I'd prefer "Grid" as a primary tab and "Console" as secondary. That better be an option.

**Comment by Jay-Rad** [comment]
Only the agents that are installed as a service will appear in the grid.  The Remotely_Desktop app only allows remote control by invite.
