### ISSUE TITLE
Preventing abuse with remote assistance

### ISSUE THREAD

**Issue by xcracing** [Jay-Rad/Remotely#40]
Is there a way to secure my server from use by unknown parties?      For instance, currently it seems that if someone discovered my URL, they could start using my server for their own production environment, or even impersonate me - this includes more nefarious characters like tech support scammers, or some unscrupulous company overwhelming my server with their support traffic.

Maybe an option to put the remote control section behind the authentication system, so it can only be accessed by logged in users?    This seems like an easy way to prevent a whole host of potential abuse issues.

**Comment by Jay-Rad** [comment]
You bring up a good point.

I'd still like the keep the option of allowing spontaneous support without needing an account (for example, on the demo server).

I'll add an option for this, which will default to "authentication required."

Thanks.  :)

**Comment by xcracing** [comment]
Thanks for a really cool and useful project!   Super cool it's done with SignalR and C#

**Comment by Jay-Rad** [comment]
Resolved in commit 6aad89e01da77712cf086d9a7894f448cad17721.  When RemoteControlRequiresAuthentication is set to true in appsettings.json, both the remote control page and the websocket endpoint will require authentication.
