### ISSUE TITLE
Invited users are created without password, how to login

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#41]
If you invite a user to an organization, they are created without password, if self registration is disabled , how could they set their password ?! or shall they reset it ?!

**Comment by Jay-Rad** [comment]
Resolved in commit 6aad89e01da77712cf086d9a7894f448cad17721.

A password reset link is normally sent with the invite email.  But, as you pointed out, it would be impossible to retrieve it if the SMTP server isn't set up correctly.

Now, when a new account is created as a result of the invite, the reset link will be visible alongside the invite link in the Organization Management page.

For security reasons, reset links won't be generated for existing accounts.  For existing accounts that are stuck in limbo as a result of this, you can manually delete them from the RemotelyUsers table in the DB.  Or, if they've never logged in before, sending another invite and deleting it will cause the account to also be deleted.
