### ISSUE TITLE
Remotely is reporting Lost Connection

### ISSUE THREAD

**Issue by agottschling** [Jay-Rad/Remotely#42]
Hey all, I installed remotely on my server and decided to try and use Apache for the reverse proxy instead of NGINX, as I already had apache running some stuff. It does seem to work, but when I log in, the dashboard console keeps saying that the connection has been lost and that I need to reload the page to reconnect. Reloading doesn't help, as the same message appears once the page reloads. 
I've attached my Apache config below, I tried to mimic the NGINX config as best I could, but maybe I missed something. 
Thanks,
Andrew

BEGIN Apache2 CONFIG:
```
<IfModule mod_ssl.c>
<VirtualHost [<IPs REMOVED.]:443 <IPs REMOVED>:443>
        ServerName remotely.mysite.com
        ServerAdmin webmaster@mysite.com

        ProxyPreserveHost On
        #Proxy Requests to Remotely Server
        <LocationMatch "/">
                ProxyPass http://localhost:5000/ 
                ProxyPassReverse http://remotely.mysite.com/
        </LocationMatch>
        <Location "/BrowserHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://remotely.mysite.com/
        </Location>

        <LocationMatch "/DeviceHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://remotely.mysite.com/
        </LocationMatch>

        <LocationMatch "/RCBrowserHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://remotely.mysite.com/
        </LocationMatch>

        <LocationMatch "/RCDeviceHub">
                ProxyPass http://localhost:5000/
                ProxyPassReverse http://remotely.mysite.com/
        </LocationMatch>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

SSLCertificateFile /etc/apache2/certs/mysite.com/fullchain.pem
SSLCertificateKeyFile /etc/apache2/certs/mysite.com/key.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
</IfModule>

**Comment by Jay-Rad** [comment]
Unfortunately, I have no experience with Apache nor the time to set it up and test.

It sounds like the websocket connection is not successfully upgrading.  It does a handshake process first over https, then upgrades to wss.

You'll notice in the [Nginx config](https://github.com/Jay-Rad/Remotely/blob/master/Utilities/Remotely_Server_Install.sh) that there's special handling for the Upgrade and Connection headers.  You'll need to replicate that part as well.

**Comment by agottschling** [comment]
Sorry that it took me so long to get back to this, but I did end up getting it to work. Attached is a stripped down config for Apache2.4 that removes everything personal to my server. Feel free to include it as an option for those who don't want or can't load Ngnix.
[Remotely A2.4 Config.conf.txt](https://github.com/Jay-Rad/Remotely/files/3390014/Remotely.A2.4.Config.conf.txt)

**Comment by Jay-Rad** [comment]
Awesome!  Thanks!  I'll include this in the Utilities folder as an example.

**Comment by Zeik0s** [comment]
Hey @Jay-Rad, please put the file in the Utilities folder. Took me quite some time to find the apache sample config. 😉

**Comment by Jay-Rad** [comment]
@Zeik0s Sorry!  I thought I did, but messed up.  I uploaded it now.  :)

**Comment by Zeik0s** [comment]
@agottschling I tried your config for apache, i am still getting the errors. I am using plain http for testing, can this be the reason?

**Comment by agottschling** [comment]
@Zeik0s This config is built for an SSL site. What errors are you gettings?

**Comment by Zeik0s** [comment]
Every few seconds a little window pops up with a message "the connection was lost, please reconnect" or something like that. I am currently not in range of the PC i am testing on.

**Comment by Zeik0s** [comment]
I know, i commented every ssl related line out, so basically it should be fine. Of course i changed the Port to 80.

**Comment by agottschling** [comment]
Another thing to check is if mod_proxy_wstunnel is enabled. If it's not, that would explain why it's not working.

**Comment by Zeik0s** [comment]
I haven't, i only enabled mod_proxy and mod_proxy_http. Will try it later, thx a lot.
