### ISSUE TITLE
Linux install without https

### ISSUE THREAD

**Issue by cwesterfield** [Jay-Rad/Remotely#44]
Is there a way to invoke `Remotely_Server_Install.sh` without https?

I already have a standalone reverse proxy that handles all my subdomains.

**Comment by Jay-Rad** [comment]
The script is only designed for the scenario where Nginx and Remotely will be on the same machine.  For other scenarios, it'd be best to do it manually.  You can use the script as a general guide while referring to Microsoft's official documentation.  I believe I put a link in the readme.

That said, you can skip the SSL/TLS cert install by entering "c" when the Certbot part of the script asks for an email.

**Comment by Jay-Rad** [comment]
Here's the link.

https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2
