### ISSUE TITLE
Issue with permissions & tags

### ISSUE THREAD

**Issue by xcracing** [Jay-Rad/Remotely#46]
Here's my scenario:

I created an admin account, setup my org, installed the agent on three machines, setup two permissions groups - "dev machines" & "servers".    Put two boxes in "dev machines", one in "servers".

I created another account and invited it into my org.    Gave it only permission to the "dev machines" group.    I see the computers I'm supposed to when logged into the secondary acct.

After a time (maybe 3 min or so) suddenly the computer in my "Servers" group will show up in my secondary acct.    As a side note, when this happens my tags are typically permanently erased as well.

If I log out, then back in, the list of available computers shows the correct boxes - but after approx 3 min, the other computer shows back up in the list again.

One final note - also, remote control does not work at all on my secondary acct.   The remote control graphic comes up, slides away, nothing happens.    I logout, login to my primary acct, and remote control works.

**Comment by Jay-Rad** [comment]
Thanks for the detailed report.  I'll get this fixed this weekend.

**Comment by Jay-Rad** [comment]
I wasn't able to resist staying up and looking into this.  I think I got all points you mentioned fixed.  I just want to do some more testing tomorrow with a rested mind.

If everything looks good tomorrow, I'll do another release.

**Comment by xcracing** [comment]
Lol I know what you mean, my mind plays the same games with me!  Have a good night and get some rest! Glad you were able to make sense of my description, nothing's worse than when someone emails me about some complex issue with nothing more than "xxxx isn't working".  Details people!

**Comment by Jay-Rad** [comment]
Thanks!  Sorry I didn't get to this yesterday.  I was doing family stuff.

The above issues should be resolved in the latest release (commit 7e7692928b2ca19eebb05eb57f999eeae979ecfc).

I'm still not happy with the permissions/groups functionality.  I put it together hastily and am hoping to completely revamp it when I have time.  Until then, let me know if there are anymore issues with the current rudimentary system.

**Comment by xcracing** [comment]
Same here.   I'll give this a shot probably later tonight.  Will let you know if I run into anything else.

**Comment by xcracing** [comment]
I must have screwed something up....   Or - did you make any changes to the db structure?  Maybe that's what's wrong.   See below:

I went to remotely.lucency.co and downloaded the "server files only".    Shut down the website in IIS, overwrote my files, Started website.

Now, when I try to remote control any newly installed agents, I get a message in the console saying "Remote control executable not found on target device".       When I try to control an existing agent install, it acts like it's going to work but I get a blank screen with Remotely in the top left.    The side panel is there but nothing works.

As a side note, before, when I downloaded the remote control client, I thought it auto populated my server name (am I remembering right?) - now it just has https.   

Other than that, the other issues that I can test seem to have been fixed.   I created two organizations and put devices in both - now if I could remote control them, I'd be in great shape!!

Thanks for any guidance you can give.

**Comment by Jay-Rad** [comment]
The remote control issue was on my end.  I set up a different build server, and the last build had some issues.  Didn't realize it until now.  I uploaded new packages that should be working correctly.  After the agents auto-update with this latest version, the remote control should start working.

The server will only auto-populate for the demo server, and only if it's the first time Remotely has ever been run.  The URL has to be hard-coded and compiled into the app or installer for that to work, so I can't make a generic one that works for everyone.

Actually, trying to make a generic binaries that don't have any server info compiled into them is the source of a couple headaches right now.  I'm still mulling over how I want to handle things for the long term.

**Comment by xcracing** [comment]
Cool - all verified working now.   I had to manually update some of my clients but maybe I didn't give them enough time.

FWIW, I'm running it on windows 10, windows 7 and Server 2012R2.    For server 2012R2 and Win7 I had to do the windows mgmt framework 5.1 update so powershell could do it's business.

Thanks again for the quick response

**Comment by Jay-Rad** [comment]
No problem!

Yeah, with a previous solution, I had a compile-on-demand service.  They'd enter their URL and company name into a form on the website, and it compiled in real-time and sent them the download link when it was done.

Unfortunately, Remotely would be too large and too resource-demanding for that.

It'd be nice if everyone already had an environment set up for building from source.  :)
