### ISSUE TITLE
Changing URL from Base URL to a folder URL

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#48]
I found that when installing Remotely in a folder it won't work, it requires Remotely to be installed on the root folder.

What do I need to change to make it work ?!

**Comment by Jay-Rad** [comment]
I'm not sure what you mean.  Could you elaborate?

**Comment by Busbar2297** [comment]
Trying to install remotely to http://server/remotely , it doesn't work bit http://server works fine.

**Comment by Jay-Rad** [comment]
I understand now.

Unfortunately, that's not possible.  The URL's "host" part needs to resolve to the Remotely application, with no paths.

If you're running it on an internal network, and "server" is the name of a machine on your network, you can just set Remotely as the default site.

If it's facing the internet, you can create a subdomain for Remotely.  So it'd be http://remotely.server.com.  That's what I've done with "https://tryremotely.lucency.co".

Does this answer your question?

**Comment by Busbar2297** [comment]
That is fine, it just prevents hosting it along multiple apps as it has to be the root one but this is fine as long as it is a known limitation
