### ISSUE TITLE
REQUEST: Change the API to connect to devices using IDs

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#49]
Can you change the API to connect to device ID instead of Device name, this will allow us to have multiple devices with the same name working nicely.

I know we shouldn't have multiple devices with the same name, but it happens.

**Comment by Jay-Rad** [comment]
This change has been made in commit 0413f8dc73a7c14092e11e5a0f47d0f92ecc78bc.

Thanks for the suggestion!
