### ISSUE TITLE
Clients on Windows 7 / PowerShell below 5.0

### ISSUE THREAD

**Issue by i3laze** [Jay-Rad/Remotely#5]
Looks like "New-GUID" was implemented in PS5.0.

Please find some time to refactor the script to support Server 2012R2 (PS4.0) and Windows 7 (PS2.0):
_New-Guid_: https://www.thomasmaurer.ch/2016/03/create-guid-using-powershell
_Expand-Archive_: https://stackoverflow.com/questions/40692024/zip-and-unzip-file-in-powershell-4

At least, PS version check should be in the script - not errors.

**Comment by Jay-Rad** [comment]
At this time, only Windows 10 is supported.

(Just FYI:  I have very limited time and resources to work on this.  I have a full time job and a family/kids.  Working on this costs me money and time away from my family.  That's why I'm only developing on current versions.)

**Comment by i3laze** [comment]
Thank you for your efforts and thoughtful answers!

**Comment by irreleph4nt** [comment]
Necrobumping to post a pretty simple solution to this problem:
Update your powershell version on a Windows 7 / 8 machine using the [right files from MS](https://docs.microsoft.com/de-de/powershell/scripting/install/installing-windows-powershell?view=powershell-6)
