### ISSUE TITLE
Crashing Avast? ... O.o ...

### ISSUE THREAD

**Issue by nittanygeek** [Jay-Rad/Remotely#50]
When attempting to remote control a machine that has Avast Business installed, it will inadvertently cause Avast to completely crash and fail on initial connect.  But then when you attempt to connect a 2nd time, it works because Avast is no longer running and trying to block the connection.  I then have to manually restart Avast Business.  Even though I've set the Remotely folder to be excluded, it still causes this panic.  Any way to remedy this with antivirus?

**Comment by Busbar2297** [comment]
Could this happen not because AV but because the behavior analysis feature ?!

**Comment by Jay-Rad** [comment]
The remote control agent will wait 10 seconds for the incoming connection, then close itself if no one has connected.  This might be what's causing Avast to crash.  Maybe Avast is preventing the connection and is in the middle of scanning the file when the app closes.

The remote control executable is located within the ScreenCast folder (under the Remotely folder).  Maybe try explicitly whitelisting that folder as well?

**Comment by Jay-Rad** [comment]
Closing as I haven't heard anything back.
