### ISSUE TITLE
Build platform for debian

### ISSUE THREAD

**Issue by Zeik0s** [Jay-Rad/Remotely#51]
How are the binary files in the server.zip for linux built? Must those be built on a windows machine or can they also be built on linux (debian)?

**Comment by Jay-Rad** [comment]
Linux binaries can be built on either Windows or Linux.  They're built using "dotnet publish --runtime linux-x64" command.  See "dotnet publish --help" for more info on that.

For more information on runtime IDs, see https://docs.microsoft.com/en-us/dotnet/core/rid-catalog.

According to the above docs, the Linux binaries should work on "Most desktop distributions like CentOS, Debian, Fedora, Ubuntu and derivatives".

I haven't tested on anything other than Ubuntu, though.

**Comment by Zeik0s** [comment]
Ok, will try it myself installing it on debian, because i think this should work too.

**Comment by risturiz** [comment]
Just for the record... Debian 10 working here with "Ubuntu_Server_Install.sh"... Only have to change:

```
wget -q https://packages.microsoft.com/config/debian/$UbuntuVersion/packages-microsoft-prod.deb
```
And comment the line:
`add-apt-repository universe`

The installer go without problems... So its very easy to have Debian_Server_install.sh too
