### ISSUE TITLE
Will Remotely work without user login?!

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#52]
Will it work, shall I run it as a service first ?!

**Comment by Busbar2297** [comment]
Just to elaborate more, the reason is that I can't get ctrl+Alt+delete working although I set the registry key manually, any thoughts ?!

**Comment by Jay-Rad** [comment]
The Ctrl+Alt+Del command can only be sent from a service.  In Remotely, it only works if the remote control session is unattended (which is started through the service).

**Comment by Busbar2297** [comment]
Yup, this is what I did and it is not working on Windows Server 2012 R2, which OS have you tested it on ?!

**Comment by Jay-Rad** [comment]
I haven't tested on Server 2012 R2.  I've tested on Windows 10, Server 2016, and Server 2019.

**Comment by Busbar2297** [comment]
let me test it.

**Comment by Zeik0s** [comment]
@Busbar2297 windows server 2012 installation of the client didn't work for me. It exited with an error. What did you do?

**Comment by Busbar2297** [comment]
@Zeik0s Are you using your own agent or the public one?!
Make sure to install .net framework 4.7.2 + .net core runtime 2.2

If you are using your own agent, make sure to have all dependencies included in the publish profile, as it doesn't include them by default, we removed some dependencies like powershell and WinRM to reduce the agent so we only need .net and core for now.

**Comment by Zeik0s** [comment]
Installed both, .net core was not installed before. But i am getting the error: 
```
Error occured:
DeviceID = (New-Guid).ToString();
 ~~~~~~~~
```

**Comment by Jay-Rad** [comment]
Make sure you have WMF 5.1 installed:  https://www.microsoft.com/en-us/download/details.aspx?id=54616
