### ISSUE TITLE
SUGGESTION: start service using Task.Run

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#53]
In OnStart Event, you you have placed:
                DeviceSocket.Connect();

if the server is not available, the service will not run, I believe that a better way to do it is throught
            Task.Run(() => loader());
Where Loader() is a void and has a while loop that tries to connect the DeviceSocket.

I do this for all of my services to avoid start issues.

**Comment by Busbar2297** [comment]
The loader method:
private static void loader()
        {
            while (true)
            {
                try
                {
                    if (OSUtils.IsWindows)
                    {
                        // Set Secure Attention Sequence policy to allow app to simulate Ctrl + Alt + Del.
                        //var subkey = Microsoft.Win32.Registry.LocalMachine.OpenSubKey(@"SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System", true);
                        //subkey.SetValue("SoftwareSASGeneration", "3", Microsoft.Win32.RegistryValueKind.DWord);
                    }
                    DeviceSocket.Connect();
                }
                catch (Exception ex)
                {
                    Logger.Write(ex);
                    System.Threading.Thread.Sleep(60000);
                    loader(); ;
                }
            }
            
        }

**Comment by Jay-Rad** [comment]
Thanks for the suggestion.  See response in #54
