### ISSUE TITLE
SUGGESTION: Fix Connect method to handle disconnects

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#54]
I faced an issue when the device initially connects then a disconnect from the network issue happen, then the agent will crash, to fix it, I have configured the connect method using this small fix:
        public static async void Connect()
        {
            try
            {
                ConnectionInfo = Utilities.GetConnectionInfo();

                HubConnection = new HubConnectionBuilder()
                    .WithUrl(ConnectionInfo.Host + "/DeviceHub")
                    .Build();

                HubConnection.Closed += HubConn_Closed;

                RegisterMessageHandlers(HubConnection);

                await HubConnection.StartAsync();

                var device = Device.Create(ConnectionInfo);

                await HubConnection.InvokeAsync("DeviceCameOnline", device);

                if (string.IsNullOrWhiteSpace(ConnectionInfo.ServerVerificationToken))
                {
                    IsServerVerified = true;
                    ConnectionInfo.ServerVerificationToken = Guid.NewGuid().ToString();
                    await HubConnection.InvokeAsync("SetServerVerificationToken", ConnectionInfo.ServerVerificationToken);
                    Utilities.SaveConnectionInfo(ConnectionInfo);
                }
                else
                {
                    await HubConnection.InvokeAsync("SendServerVerificationToken");
                }

                if (HeartbeatTimer != null)
                {
                    HeartbeatTimer.Stop();
                }
                HeartbeatTimer = new Timer(300000);
                HeartbeatTimer.Elapsed += HeartbeatTimer_Elapsed;
                HeartbeatTimer.Start();
            }
            catch (Exception ex)
            {

                Console.WriteLine(ex.Message);
                System.Threading.Thread.Sleep(10000);
                Connect();

            }
        }

**Comment by Jay-Rad** [comment]
Thanks for the suggestion.

However, I'm intentionally rethrowing exceptions and letting the app crash, which generates an event in the Windows Event Viewer.

In the above example, an exception within the catch block would cause an unhandled exception.  So it would need to be structured differently.

When I have time, I'll look into writing directly to the Event Viewer and changing the error handling.

**Comment by Busbar2297** [comment]
It would through an error, waits then tries to connect, it works nicely with my other apps

**Comment by Jay-Rad** [comment]
I understand.  :)  The only reason for allowing the exception is to capture it in the Event Viewer.

The service is created with the auto-recovery option, so it restarts after 5 seconds and tries again.

I'll look into refactoring soon.

**Comment by Jay-Rad** [comment]
This has been refactored.
