### ISSUE TITLE
Adding Requester Name to SendScreenCastRequestToDevice

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#55]
Somehow, and not sure why, I don't receive the requester name in the request, I do this because I authenticate the user locally in the agent and display a popup message to request the control, this wasn't fixed until I configured SendScreenCastRequestToDevice as below:
        public async Task SendScreenCastRequestToDevice(string screenCasterID, string requesterName, int remoteControlMode)
        {
            requesterName =  Context?.User?.Identity?.Name;
            if ((RemoteControlMode)remoteControlMode == RemoteControlMode.Normal)
            {
                if (!RCDeviceSocketHub.AttendedSessionList.ContainsKey(screenCasterID))
                {
                    await Clients.Caller.SendAsync("SessionIDNotFound");
                    return;
                }

                screenCasterID = RCDeviceSocketHub.AttendedSessionList[screenCasterID];
            }
           
            DataService.WriteEvent(new EventLog()
            {
                EventType = EventTypes.Info,
                TimeStamp = DateTime.Now,
                Message = $"Remote control session requested.  " +
                                $"Connection ID: {Context.ConnectionId}. User ID: {Context.UserIdentifier}.  " +
                                $"Screen Caster ID: {screenCasterID}.  " + 
                                $"Mode: {((RemoteControlMode)remoteControlMode).ToString()}.  " + 
                                $"Login ID (if logged in): {Context?.User?.Identity?.Name}.  " +
                                $"Rquester Name (if specified): {requesterName}.  " +
                                $"Requester IP Address: " + Context?.GetHttpContext()?.Connection?.RemoteIpAddress?.ToString()
            });
            _dataExchange.SessionInfo.TryAdd(Context.ConnectionId, Context?.User?.Identity?.Name);
            ScreenCasterID = screenCasterID;
            Mode = (RemoteControlMode)remoteControlMode;
            RequesterName = requesterName;
            if (Mode == RemoteControlMode.Unattended)
            {
                await RCDeviceHub.Clients.Client(screenCasterID).SendAsync("GetScreenCast", Context.ConnectionId, requesterName);
            }
            else
            {
                await Clients.Caller.SendAsync("RequestingScreenCast");
                await RCDeviceHub.Clients.Client(screenCasterID).SendAsync("RequestScreenCast", Context.ConnectionId, requesterName);
            }
        }

Please ignore the dataexchange part as we use it internally to exchange data beteeen APIs and services in our flavor of Remotely.

**Comment by Jay-Rad** [comment]
Requester name is only included when typed into the Remote Control web page.
