### ISSUE TITLE
Won't load correctly on iOS

### ISSUE THREAD

**Issue by bubblesnout** [Jay-Rad/Remotely#57]
Loving this so far, working great on all my PCs!

I've got Remotely set up via Docker on my Synology NAS (I can provide Dockerfile/scripts if needed) which is working perfectly on all my PCs, I've installed the silent agent on all of them and can successfully jump between them via a regular web browser.

When I try and load the page on my iPhone however it simply gets stuck on "Loading resources"
![2019-07-29_170839](https://user-images.githubusercontent.com/6344088/62028438-98e11c80-b223-11e9-83c7-42585c18ecde.png)

I've tried building the project myself and using that, different linux flavours (Ubuntu 18.04 & 19.04, Alpine 3.9) and the results are always the same. I'm using nginx as a reverse proxy (built in to the Synology) and the nginx config for the domain mirrors that in the Ubuntu automatic install script.

Any ideas?

**Comment by bubblesnout** [comment]
Note: I have also tried this on an iPad, and with different browsers (Safari, Chrome, Firefox) and they all have the same result.

**Comment by Jay-Rad** [comment]
This sounds like it's a JavaScript issue (e.g. using a language feature that doesn't exist in a particular browser).  Which is odd, because I'm using TypeScript, which should take care of any necessary polyfills.  It's also odd that it fails in the other browsers on the iPad.

Unfortunately, I don't have an iOS device to test on.  Are you able to get to the browser console on the iPad?  I'd be interested to see what errors it's showing.

**Comment by bubblesnout** [comment]
Having a quick look it seems you can only run the debugger and dev tools with iOS Safari by attaching it through a Mac with a USB cable. I’ll have to have a look around and see if there’s another browser that offers it on-device (and exhibits the same problem). Leave it with me and I’ll see what I can find.

**Comment by bubblesnout** [comment]
Apologies for the delay with this, I was trying to figure out a way to debug directly on my iPhone but didn't have any luck.
I've managed to confirm however that this issue occurs in *any* WebKit based browser. I'm assuming you are developing on Windows, so what I've found is that you can use a Windows build of a WebKit testing browser, the current latest build can be downloaded here: https://s3-us-west-2.amazonaws.com/archives.webkit.org/win-x86_64-release/248834.zip

Just extract the zip and run MiniBrowser.exe (you may need iTunes installed, not entirely sure)

I've had a quick test myself and the Web Inspector shows the attached error.
![2019-08-19_100338](https://user-images.githubusercontent.com/6344088/63232198-e8d26280-c268-11e9-93c7-126a2320b06c.png)
