### ISSUE TITLE
LDAP or Active Directory authentification

### ISSUE THREAD

**Issue by FelR** [Jay-Rad/Remotely#58]
First of all, I want to thank you for this great piece of software. 

For usage in my homelab it would be great if this software would support some kind of central credential management solution like LDAP or Active Directoy, so you don't have to manage multiple accounts for the same user. 

Would it be possible for you to implement it in the future?

**Comment by Jay-Rad** [comment]
I've recently starting working for a commercial RMM, and I won't be putting much time toward Remotely.  It is mostly in maintenance mode now.
