### ISSUE TITLE
Unattended remote won't work

### ISSUE THREAD

**Issue by mmeinert** [Jay-Rad/Remotely#59]
Did an install on a fresh VPS 18.04.3 ubuntu server, classic remote control with client sharing app works out of the box but unattended won't.
The resident agent is installed on 3 Windows 10 machine, they are shown in the grid as online and when I click on "Remote Control", "Starting remote control" is shown, in console tab : "Launching remote control on client device..." and "Starting remote control" but nothing appears.

I tried :
- to populate a link myself with https://team.polbru.be/RemoteControl?clientID=AAA&serviceID=BBB (AAA and BBB found in ConnectionInfo.json). Interface remains black, left command menu is shown.
- multiple browsers
- in appsettings.json : changing "RemoteControlRequiresAuthentication" to false
- deactivate firewall and antivirus software on the client side

With LogLevel set to "Debug" I don't see anything wrong in nginx logs (but it's maybe shown elsewhere (?))

Any idea where I can look for this ?

PS.:Anyway, thank you for this code...

**Comment by Jay-Rad** [comment]
There appears to be a compatibility issue between .NET Framework (Windows) and .NET Core (cross-platform).  It's only affecting the unattended agent, and only when connecting to a Linux server.  This wasn't always an issue, and I'm not sure when it was introduced.

I'll investigate after I get off work.

For future reference, agent logs are in C:\Windows\Temp\Remotely_Logs.txt.

**Comment by mmeinert** [comment]
Did an update with the new release with stopping the service, then overwrite the files and restarting the service and it crashed.
I made a new install and same crash
![image](https://user-images.githubusercontent.com/2050640/65222621-c2018900-dabf-11e9-9041-d905be87cf22.png)
Any log needed ?
Thank you for the followup

**Comment by Jay-Rad** [comment]
I'm guessing the file permissions need to be changed.  Try the following (assuming you used the default path for the files):

`setfacl -R -m u:www-data:rwx /var/www/remotely`
`chown -R www-data:www-data /var/www/remotely`

**Comment by mmeinert** [comment]
You guessed right ;)
Works like a charm now !
