### ISSUE TITLE
Dockerize server

### ISSUE THREAD

**Issue by davidsarkany** [Jay-Rad/Remotely#60]
Please create docker version for server.

**Comment by Jay-Rad** [comment]
I've recently starting working for a commercial RMM, and I won't be putting much time toward Remotely. It is mostly in maintenance mode now.

**Comment by tylerrbrown** [comment]
I took a stab at it:

FROM ubuntu:18.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y apt-utils 2>&1 | grep -v "debconf: delaying package configuration, since apt-utils is not installed" \
    && apt-get install -y \
        acl \
        wget \
        unzip \
        ffmpeg \
        libicu60 \
        libssl1.0 \
        libc6-dev \
        libgdiplus \
    && wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb \
    && apt-get update -y \
    && apt-get install -y \
        apt-transport-https \
        aspnetcore-runtime-3.1 \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc \
    && rm -Rf /usr/share/man \
    && apt-get clean \
    && mkdir -p "/var/www/remotely" \
    && wget -q https://github.com/Jay-Rad/Remotely/releases/latest/download/Remotely_Server_Linux-x64.zip -O Remotely_Server_Linux-x64.zip \
    && unzip -qq -o Remotely_Server_Linux-x64.zip -d "/var/www/remotely" \
    && rm Remotely_Server_Linux-x64.zip \
    && setfacl -R -m u:www-data:rwx "/var/www/remotely" \
    && chown -R www-data:www-data "/var/www/remotely"

EXPOSE 5000/tcp

ENV ASPNETCORE_URLS="http://*:5000"
ENV ASPNETCORE_ENVIRONMENT="Production"

WORKDIR /var/www/remotely/
ENTRYPOINT ["dotnet", "Remotely_Server.dll"]
