### ISSUE TITLE
remote control not working while screen changing

### ISSUE THREAD

**Issue by romansuda** [Jay-Rad/Remotely#61]
Hi,
I have a problem with remote controlling while on remote screen is something changing. Eg graph in taskmgr, or video.. I think there is a problem with continuously jpeg sendings from target PC to the browser, but browser doesn't send cursor's positions. Bandwidth is too high, maybe will be better use RDP library ( like in here https://www.c-sharpcorner.com/uploadfile/ulricht/how-to-create-a-simple-screen-sharing-application-in-C-Sharp/ ).

thanks

**Comment by Jay-Rad** [comment]
Thank you for the suggestion.  However, I've stopped most of my work on Remotely, and I won't be making any big changes or new features.  Not for free, anyway.

This is the first I've heard of the issue you're describing.  As you can see [here](https://imgur.com/a/uIc9Tfv), remote control works fine with a video going.

The bandwidth is higher than RDP, yes.  But it's acceptable for my uses.

**Comment by BlijeGub** [comment]
I think I have the same problem. On one of my machines the screen keeps turning black when anything on the screen changes. Unless the mouse keeps moving the screen will stay black.
