### ISSUE TITLE
User can hijack other users by inviting them into Organization

### ISSUE THREAD

**Issue by McChicken2020** [Jay-Rad/Remotely#69]
If you invite somebody into an organization when they already have their own (with computers), and they click the link in the email, it will change their organization and they will lose access to all their existing computers.

**Comment by Jay-Rad** [comment]
Hijacking implies stealing, which isn't the case here.  :D  What you've described is being tricked into leaving an organization. 

I have tentative plans to overhaul the invite and user management system.  In the meantime, I'd recommend keeping the MaxOrganizationCount to the default setting of 1, which makes the situation you're describing impossible.

But if it does happen, an admin can invite the user back in.  Or the server administrator can revert the change manually in SQL.

**Comment by McChicken2020** [comment]
A dirty fix would be to prevent inviting existing users into an organization. 

```
if (!DataService.DoesUserExist(invite.InvitedUser))
            {
//Generate New User
}
else
{
return BadRequest("This User Already Has an Organization. Please Use a Different Email.");
}
```

**Comment by Jay-Rad** [comment]
For what it's worth, I added a very obvious warning on there.


![Invite Warning](https://i.imgur.com/TPIOHlA.png "Invite Warning")
