### ISSUE TITLE
Linux Client

### ISSUE THREAD

**Issue by gvsurenderreddy** [Jay-Rad/Remotely#7]
Hello sir

Can you give linux 64 bit and 32 portable Client please

**Comment by Jay-Rad** [comment]
Most Linux distributions are ending support for 32-bit.  As such, I don't want to add the burden of supporting and releasing 32-bit clients.

**Comment by gvsurenderreddy** [comment]
Sir can you please tell me how can i build from source for Linux Client 32Bit please help

**Comment by Jay-Rad** [comment]
From the Remotely_Agent directory, run: 

`dotnet publish  --runtime linux-x86 --configuration Release`
