### ISSUE TITLE
Configuration Setting for Client HostName in Downloadable Installer Scripts

### ISSUE THREAD

**Issue by tylerrbrown** [Jay-Rad/Remotely#72]
I am running Remotely server behind a proxy server which offloads TLS, and talks to the backend on plain HTTP. From Remotely Server's perspective TLS is not in use, but from the client's perspective it is. So when you go to download the client installation scripts it builds in a URL like:

HostName="http://remotely.someplace.com"

...I need to override this somehow to make it produce:

HostName="https://remotely.someplace.com"

...in the downloadable install scripts. I suspect there is another way to do this that I am just missing, but I didn't see anything in the appsettings.json file. 

Thanks,

Tyler

**Comment by Jay-Rad** [comment]
Hi, Tyler.

This would normally be set automatically via the X-Forwarded-Proto header.  If the headers are forwarded from the proxy server, the Remotely Server will see the correct scheme (http/https).  I'm not sure what other factors might contribute to it not working correctly, though.  I haven't been able to reproduce it.

I added some logic to it tonight.  If you have RedirectToHttps set to true in appsettings, it will insert "https" there regardless of what it sees in the request scheme.

Let me know if that doesn't help!  :)

**Comment by tylerrbrown** [comment]
Just now got around to checking this and it fixed it!!!!

...also I "dockertized" linux server successfully.
