### ISSUE TITLE
Options to temporarily block user's input and black screen, like TeamViewer

### ISSUE THREAD

**Issue by paulocoghi** [Jay-Rad/Remotely#74]
I would like to know if it is possible to temporarily block user's input and/or makes his screen black, on sessions by invite.

_(even with third party softwares or scripts)_

Thanks!

**Comment by Jay-Rad** [comment]
Hiya.

I just added the ability to block user's input.

I couldn't find a good way of blacking out the screen, though.  I'm not sure if I'll have time to look further into it.  I'll comment back here if I do.

Thanks!

**Comment by paulocoghi** [comment]
Thank you!

**Comment by paulocoghi** [comment]
@Jay-Rad with the feature of block users's input on sessions by invite, Remotely becomes the go-to software to do remote desktop.

Combining with the other features, like optional use of WebRTC and scripting, Remotely is a 5 star software.

**Comment by Jay-Rad** [comment]
Wow, thanks for the compliment!  Much appreciated.  :)

**Comment by MatthK** [comment]
I know it's an old thread. Is that with the blacking out the screen something that won't see the day of the light? It would be really a very nice feature. Ideally, it would be something that could be configured as "standard" for a client.
I'm often accessing my work computer from remote, and then everybody can see what's happening on my screen. So when I open confidential files, anyone in front of my desk can see and I have no idea if someone is watching that. So the ability to just show a black screen would be really a great plus.
