### ISSUE TITLE
users

### ISSUE THREAD

**Issue by robulanetteam** [Jay-Rad/Remotely#75]
Hello! Can you add functionality for distributing access between users by groups? So that users can interact and see only their groups?

**Comment by Jay-Rad** [comment]
Hiya!

I had an ad-hoc permission system in the past.  It was hastily-implemented and not put together very well, so I removed it.

I intend to put something back in.  I don't have an estimated time yet, though.

**Comment by Jay-Rad** [comment]
I've added permissions back in.  You can add users to device groups to limit access to them.
