### ISSUE TITLE
Connect to Different server name through API

### ISSUE THREAD

**Issue by Busbar2297** [Jay-Rad/Remotely#76]
Hi,
I found strange issue, I can connect to the server using FQDN and authenticate and acquire a token and connection URL, but it doesn't work in connection as connection is not relayed to the client.

If I use IP it works, what could be the reason considering that client can connect and registered with the server via FQDN?!

**Comment by Jay-Rad** [comment]
If I'm understanding the issue correctly, it sounds like you're calling the API via JavaScript from another website.

In order for that to work, you must add the website's origin (base URL) to the TrustedCorsOrigins array in the appsettings.
