### ISSUE TITLE
Broken links on new website

### ISSUE THREAD

**Issue by swilkey** [Jay-Rad/Remotely#77]
Hi Jay-Rad,

Thanks for your work on this tool.   You are obviously in the middle of a domain migration because a few weeks ago I bookmarked this link https://remotely.lucency.co/ which is still listed here https://lucency.co/Apps but now it doesn't work.

Googling found me https://remotely.one, however the links on that page for downloading clients don't work as they go to a non-existent domain: 
https://tryremotely.lucency.co/Downloads/Win-x64/Remotely_Desktop.exe
https://tryremotely.lucency.co/Downloads/Win-x86/Remotely_Desktop.exe
https://tryremotely.lucency.co/Downloads/Remotely_Desktop

Are you able to provide the new links?

Thanks,
Stephen

**Comment by Jay-Rad** [comment]
Hi, Stephen.

Thanks for the heads-up.  I am indeed in the middle of a domain migration.  There have been some pretty significant changes to Remotely too, and I'm working out some kinks at the moment.

I've updated the website, though.  Here are the new links:

https://app.remotely.one/Downloads/Win-x64/Remotely_Desktop.exe
https://app.remotely.one/Downloads/Win-x86/Remotely_Desktop.exe
https://app.remotely.one/Downloads/Remotely_Desktop

Thanks!

- Jared

- Jared

**Comment by swilkey** [comment]
Thanks very much Jared

------ Original Message ------
