### ISSUE TITLE
How to enable recordings

### ISSUE THREAD

**Issue by swilkey** [Jay-Rad/Remotely#79]
Hi again Jared,

I've been doing more testing, and I cannot see how I would enable a recording of a remote control session.  It looks like it is only possible to be done for every single session in the server settings, but not enabled for individual sessions.  Is this correct?

Regards,
Stephen

**Comment by Jay-Rad** [comment]
That's correct.  There's no option for recording individual sessions at the moment.

**Comment by swilkey** [comment]
No problem, just trying to understand what it is designed to do.  thanks for the quick reply!
