### ISSUE TITLE
Session recordings

### ISSUE THREAD

**Issue by Logicman111** [Jay-Rad/Remotely#85]
Hi,

I'm not sure what I'm doing wrong but I've tried enabling sessions recording on a Windows server and on Ubuntu with the same results. The directories for the sessions are created correctly, so it's not a permission problem, but on Windows I get an empty file and on Ubuntu no file at all. I have all the files required installed.

What I'm missing?

Thanks.

**Comment by Logicman111** [comment]
Found that the problem on Ubuntu is that you're calling ffmpeg.exe instead of ffmpeg. There's no operating system detection for this in the code. but once this is changed it works very nicely.

**Comment by Jay-Rad** [comment]
Doh!  Thanks for the catch!  :)  I'll add a switch for this.
