### ISSUE TITLE
IO Exception During Install

### ISSUE THREAD

**Issue by tedtms** [Jay-Rad/Remotely#87]
Hey! Nice to see all the great improvements since I looked at this project last, especially the compiled installer! Unfortunately, that's actually what my issue is with...

I'm trying to install Remotely on my Windows 10 desktop. The installer says the installation is successful, and the client shows up (with stats) in my Remotely server. But when I go to remote control, the server tells me "Executable not found on device." 

All of the installation files are in the right Program Files directory, and the Agent and service are both running. The client even shows up as online with stats like memory, disk usage, etc. Below is an Error I see in the install logs -- I searched it quick, and what I'm seeing is an issue when trying to move things across volumes using dotnet core. My Windows Users directory is hardlinked to another drive, which appears seamless to the OS but is obviously on another volume. Could this be what's throwing the error for the installer? 

`2020-03-16 20:55:14.671	[ERROR]	Source and destination path must have identical roots. Move will not work across volumes.	   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost) at Remotely.Agent.Installer.Win.Services.InstallerService <DownloadRemotelyAgent>d__23.MoveNext()	mscorlib`

Thanks for any input you can give! I know this is a special issue, so if there's just a workaround or something I can use for this machine (like a manual install), that would be awesome!!

Ted

**Comment by tedtms** [comment]
Saw your changelog comment "Change directory move to copy" and figured you saw my issue ticket. Just updated and tried the installation again - worked flawlessly, no IO exceptions and no remote control errors.

Thanks!

**Comment by Jay-Rad** [comment]
Haha!  You beat me to it.

Thanks.  :)
