### ISSUE TITLE
Bug: users are seeing computers from device groups they are not assigned to

### ISSUE THREAD

**Issue by captainhook** [Jay-Rad/Remotely#88]
- I have setup a server on Azure.
- I have connected 10 PCs to the server by installing client on each.
- For each of the computers I have created a device group and added the computer to the device group.
- For each of the device groups I have added one user to it.

Once the user logs in, it only shows 1 device (the only one they are assigned to). However after a few seconds the list of devices updates with one of the other PCs on the network... this continues until it populates with all the devices on the network. And the users are able to click on the remote control button and remote control every PC. Very bizarre.

Is anyone else experiencing this or know a fix/workaround?

Many thanks!

**Comment by captainhook** [comment]
I thought I searched all the issues but it looks like I missed #46 by @xcracing

I have updated to v2020.03.17 Release by running Remotely_Server_Install.sh again. But issue is persisting.

**Comment by Jay-Rad** [comment]
Should be fixed now in https://github.com/Jay-Rad/Remotely/releases/tag/v2020.03.18.

Let me know!  :)

**Comment by captainhook** [comment]
You are a freaking star, Jared! I will update now and get the charity staff to test tomorrow morning, and feedback tomorrow.

**Comment by captainhook** [comment]
Thanks, Jared. Confirmed that this is working now. It still displays all computers on the network - which is fine - but it does not allow users to remote access any computers they are not assigned to.

Perhaps later we can have a notice which tells the users they do not have access/an option to not list the other computers at all.

**Comment by Jay-Rad** [comment]
Can you try restarting the service?  "sudo systemctl restart remotely"

The changes didn't take effect on my Linux box until I restarted the service.  I'll add that to the install script (it's currently just doing "start").

**Comment by captainhook** [comment]
It works after that. Thank you :)
