### ISSUE TITLE
Users are able to change the device's device group.

### ISSUE THREAD

**Issue by captainhook** [Jay-Rad/Remotely#89]
Currently the device list populates with all devices in the organisation even if the user does not have access to a device. The user can then edit any device and change the 'Device Group' to either 'None' or any of the device groups they have access to.

Version: v2020.03.18

Happy to test further if you need help debugging.

**Comment by Jay-Rad** [comment]
Same with my previous comment.  This should be fixed once the service is restarted and using the latest files.

When trying to edit a device you don't have access to, you'll just get a blank screen and a 401 (unauthorized) return code.  There will also be the following entry in the server logs that admins can see:

"Edit device attempted by unauthorized user. Device ID: 82f5cd38-6247-4f90-a300-094e2d765b4f. User Name: myotheremail@gmail.com."

**Comment by Jay-Rad** [comment]
And just to clarify, the device shouldn't be in the device list if they don't have access.  The above would happen if they knew the device GUID and tried to navigate to the edit page manually.

**Comment by Jay-Rad** [comment]
I'm assuming this one was fixed too.  :)

**Comment by captainhook** [comment]
It was indeed, thank you :)
