### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by dsinfinite** [Jay-Rad/Remotely#96]
Error:
Checking firewall rules for HTTP/HTTPS...
C:\Users\administrator\Downloads\Install-RemotelyServer.ps1 : Cannot bind argument to parameter 'Path'
because it is an empty string.
    + CategoryInfo          : InvalidData: (:) [Install-RemotelyServer.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Install-RemotelyServer.ps1

Possible cause: Website path is C:\Data\Web Sites\Remotely

**Comment by Jay-Rad** [comment]
It looks like the $WacsPath parameter is an empty string.  It must be null or a valid path to wacs.exe (Windows ACME Simple), which can be used to obtain and install a Let's Encrypt certificate automatically.

I added comments to the params in the script.
