### ISSUE TITLE
Enhancement request: Notes and Custom Properties

### ISSUE THREAD

**Issue by tedtms** [Jay-Rad/Remotely#97]
Would it be possible to have custom properties that or even just a notes field that could be assigned to devices in the Grid? That way, we have more than just device groups and aliases to go off of when accessing machines?

That would be particularly useful for people who support several machines and need to keep specific notes about them like, what network medium they're accessed through, location, etc.

Thanks!
Ted

**Comment by Jay-Rad** [comment]
Sure.  I'll work on this next.  :)

**Comment by Jay-Rad** [comment]
This has been added in latest Alerts release.  You can edit Notes in the Edit Device page.  You can also filter on the Notes property in the Select command on the console.
