### ISSUE TITLE
edit cshtml file

### ISSUE THREAD

**Issue by sylvainpaquet** [Jay-Rad/Remotely#98]
Hello
Excuse me if my english is not good because i'm french
Already thank you for this great project, it's been a while since I was looking for something similar.
I installed remotely on Ubuntu and everything works perfectly. ;)
But I have a question I installed via the command remotely_server_install.sh => ok
but this has installed in english version which is normal, the goal is that i would like to change the words in english to french but i can't find the cshtml files on ubuntu
do you know where it is or should i go back to the sources, modify them and redo the installation
cordially

**Comment by Jay-Rad** [comment]
Hello!

The CSHTML files are compiled into the DLLs.  The only way to modify them is from source code, then recompile.  Hope that helps!

**Comment by sylvainpaquet** [comment]
Hello jay-rad
I made the changes and recompile
Do I have to redo the installation or simply copy the files found in the wwwroot folder on ubuntu

thank you
